sudo: required
language: generic
os: linux
dist: xenial      # or focal (Ubuntu 20.04)
services:
  - docker

before_install:
  - docker build -t hasham916/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hasham916/docker-react npm run test
