sudo: required 
servicers:
      - docker 


before_install:
      - docker build -t Skill1/docker-react -f Dockerfile.dev .

script:
      - docker run -e CI=true Skill1/docker-react npm run test      