sudo: required
language: generic
os: linux
dist: xenial      # or focal (Ubuntu 20.04)
services:
  - docker

before_install:
  - docker build -t hasham916/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hasham916/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name:  
  bucket_path: "docker"
  on:
     branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  SECRET_ACCESS_KEY: "$AWS_SECRET_KEY"

